# ============================================================================
# CrossBridge Unified Configuration File
# ============================================================================
# Single source of truth for all CrossBridge configuration
# Supports environment variable substitution: ${VAR_NAME:-default_value}
# ============================================================================

crossbridge:
  # ──────────────────────────────────────────────────────────────────────────
  # CORE SETTINGS
  # ──────────────────────────────────────────────────────────────────────────
  
  # Operational mode: 'migration' or 'observer'
  mode: observer
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # APPLICATION TRACKING
  # ──────────────────────────────────────────────────────────────────────────
  
  application:
    product_name: ${PRODUCT_NAME:-CrossBridgeApp}
    application_version: ${APP_VERSION:-v0.2.0}
    environment: ${ENVIRONMENT:-test}
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # DATABASE CONFIGURATION
  # ──────────────────────────────────────────────────────────────────────────
  
  database:
    enabled: true
    host: ${CROSSBRIDGE_DB_HOST:-10.60.67.247}
    port: ${CROSSBRIDGE_DB_PORT:-5432}
    database: ${CROSSBRIDGE_DB_NAME:-cbridge-sidecar-stage1-unit-test}
    user: ${CROSSBRIDGE_DB_USER:-postgres}
    password: ${CROSSBRIDGE_DB_PASSWORD:-admin}
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # AI / LLM CONFIGURATION
  # ──────────────────────────────────────────────────────────────────────────
  
  ai:
    enabled: true
    provider: ollama
    
    # Ollama configuration (local deepseek)
    ollama:
      base_url: http://localhost:11434
      model: deepseek-coder:6.7b
      timeout: 120
      max_tokens: 300
      temperature: 0.7
    
    # OpenAI configuration (disabled - using ollama instead)
    api_key: ${OPENAI_API_KEY}
    model: gpt-3.5-turbo
    temperature: 0.7
    max_tokens: 2048
    timeout: 60
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # SEMANTIC SEARCH & TEST INTELLIGENCE
  # ──────────────────────────────────────────────────────────────────────────
  
  semantic_search:
    enabled: true
    provider_type: local
    
    # Local embedding configuration (sentence-transformers)
    local:
      model: all-MiniLM-L6-v2
      device: cpu
    
    # OpenAI configuration (disabled - using local instead)
    openai:
      api_key: ${OPENAI_API_KEY}
      model: text-embedding-3-large
      dimensions: 3072
    
    search:
      max_tokens: 8000
      min_similarity_score: 0.7
      default_top_k: 10
      api_timeout: 30
      retry_attempts: 3
      batch_size: 100
    
    vector_store:
      type: pgvector
      index_type: ivfflat
      index_lists: 100
      create_index_threshold: 1000
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # EXECUTION INTELLIGENCE
  # ──────────────────────────────────────────────────────────────────────────
  
  execution:
    framework: robot
    source_root: ./CloudConsole
    
    logs:
      automation:
        - ./CloudConsole/tests/TestRunners/results/output.xml
        - ./output.xml
      application: []
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # FLAKY TEST DETECTION
  # ──────────────────────────────────────────────────────────────────────────
  
  flaky_detection:
    enabled: true
    n_estimators: 200
    contamination: 0.1
    random_state: 42
    min_executions_reliable: 15
    min_executions_confident: 30
    min_confidence_threshold: 0.5
    execution_window_size: 50
    recent_window_size: 10
    auto_retrain: true
    retrain_threshold: 100
    model_version: "1.0.0"
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # OBSERVER MODE
  # ──────────────────────────────────────────────────────────────────────────
  
  observer:
    auto_detect_new_tests: true
    update_coverage_graph: true
    detect_drift: true
    flaky_threshold: 0.15
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # INTELLIGENCE FEATURES
  # ──────────────────────────────────────────────────────────────────────────
  
  intelligence:
    ai_enabled: true
    detect_coverage_gaps: true
    detect_redundant_tests: true
    risk_based_recommendations: true
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # FRAMEWORK-SPECIFIC SETTINGS
  # ──────────────────────────────────────────────────────────────────────────
  
  frameworks:
    robot:
      enabled: true
      auto_instrument_api_calls: true
      auto_instrument_ui_interactions: true
      capture_network_traffic: false
      track_keywords: true
      track_api_calls: true
  
  
  # ──────────────────────────────────────────────────────────────────────────
  # LOGGING CONFIGURATION
  # ──────────────────────────────────────────────────────────────────────────
  
  logging:
    level: INFO
    format: detailed
    log_to_file: true
    log_file_path: logs/crossbridge.log
    log_to_console: true
    max_file_size_mb: 10
    backup_count: 5
