"""
Grafana Dashboard Troubleshooting & Setup

This script will help you fix the blank dashboard issue
"""

print("=" * 70)
print("Grafana Dashboard Troubleshooting Guide")
print("=" * 70)
print()

print("✅ Step 1: Verify Data Exists")
print("-" * 70)
print("Run this first to confirm data is in database:")
print("  python verify_version_data.py")
print()

print("✅ Step 2: Import the SIMPLE Dashboard (Recommended)")
print("-" * 70)
print("The original dashboard has complex datasource references.")
print("Use the simplified version instead:")
print()
print("1. In Grafana, go to: Dashboards → Import")
print("2. Click 'Upload JSON file'")
print("3. Select: grafana/dashboard_version_simple.json")
print("4. When prompted for datasource:")
print("   - Look for your PostgreSQL datasource in dropdown")
print("   - It might be named: 'PostgreSQL', 'postgres', or similar")
print("5. Click 'Import'")
print()

print("✅ Step 3: Set Time Range")
print("-" * 70)
print("After importing:")
print("1. Top-right corner: Click time range dropdown")
print("2. Select: 'Last 30 days' or 'Last 7 days'")
print("3. Click 'Apply'")
print()

print("✅ Step 4: Check Datasource Configuration")
print("-" * 70)
print("If still blank:")
print("1. In Grafana: Configuration (gear icon) → Data Sources")
print("2. Click your PostgreSQL datasource")
print("3. Verify settings:")
print("   Host: 10.55.12.99:5432")
print("   Database: udp-native-webservices-automation")
print("   User: postgres")
print("   SSL Mode: disable (usually)")
print("4. Click 'Save & Test' - should show 'Database Connection OK'")
print()

print("✅ Step 5: Test Query Directly")
print("-" * 70)
print("In Grafana:")
print("1. Go to: Explore (compass icon)")
print("2. Select your PostgreSQL datasource")
print("3. Switch to 'Code' mode")
print("4. Paste this query:")
print()
print("   SELECT application_version, COUNT(*)")
print("   FROM test_execution_event")
print("   WHERE event_type = 'test_end'")
print("   GROUP BY application_version;")
print()
print("5. Click 'Run query'")
print("6. You should see: 1.0.0 (20), 2.0.0 (25), 2.1.0 (30), 3.2.0 (15)")
print()

print("✅ Step 6: Dashboard Panels to Check")
print("-" * 70)
print("The simplified dashboard has 9 panels:")
print("  1. Test Coverage by Version (bar chart)")
print("  2. Test Distribution by Product (pie chart)")
print("  3. Version Comparison Table")
print("  4-7. Stats panels (counts)")
print("  8. Pass Rate Comparison (bar chart)")
print("  9. Environment-wise Pass Rates (table)")
print()

print("✅ Common Issues & Fixes")
print("-" * 70)
print()
print("Issue 1: 'No Data' message")
print("  Fix: Expand time range to 'Last 30 days'")
print()
print("Issue 2: Red 'Query Error' message")
print("  Fix: Check datasource connection in step 4")
print()
print("Issue 3: Dashboard imports but panels are grey")
print("  Fix: Edit any panel → Click datasource dropdown → Select your datasource")
print()
print("Issue 4: Some panels work, others don't")
print("  Fix: Each panel might need datasource selected individually")
print("       Click panel title → Edit → Select datasource")
print()

print("=" * 70)
print("Quick Fix: Use Simplified Dashboard")
print("=" * 70)
print()
print("File: grafana/dashboard_version_simple.json")
print("This version:")
print("  ✓ Simpler queries (no time filters)")
print("  ✓ No complex datasource UIDs")
print("  ✓ 9 panels instead of 10")
print("  ✓ Works with any PostgreSQL datasource")
print()

print("=" * 70)
print("Need more help? Check these:")
print("=" * 70)
print("• GRAFANA_VERSION_DASHBOARD_GUIDE.md - Complete guide")
print("• Run: python test_dashboard_queries.py - Verify queries work")
print("• Grafana docs: https://grafana.com/docs/")
print("=" * 70)
