"""
CrossBridge Playwright Hook

Optional Playwright hooks that emit execution events to CrossBridge observer.

Installation (JavaScript/TypeScript):
    
    In playwright.config.ts:
    ```typescript
    import { defineConfig } from '@playwright/test';
    import { CrossBridgeReporter } from './crossbridge-playwright-reporter';
    
    export default defineConfig({
      reporter: [
        ['list'],
        [CrossBridgeReporter, { projectId: 'my-project' }]
      ]
    });
    ```

The hook is completely optional and non-blocking.
Tests run normally even if CrossBridge observer is unavailable.
"""

# This is a Python file that generates the TypeScript/JavaScript hook code
# The actual hook runs in Node.js environment

PLAYWRIGHT_TYPESCRIPT_HOOK = """
// crossbridge-playwright-reporter.ts
// Generated by CrossBridge - Playwright Event Reporter

import { Reporter, TestCase, TestResult, FullResult } from '@playwright/test/reporter';
import fetch from 'node-fetch';

interface CrossBridgeConfig {
  projectId: string;
  observerUrl?: string;
  enabled?: boolean;
}

interface CrossBridgeEvent {
  event_type: string;
  framework: string;
  test_id: string;
  timestamp: string;
  status?: string;
  duration_ms?: number;
  error_message?: string;
  metadata?: Record<string, any>;
  application_version?: string;
  product_name?: string;
  environment?: string;
}

class CrossBridgeReporter implements Reporter {
  private config: CrossBridgeConfig;
  private observerUrl: string;
  private enabled: boolean;

  constructor(config: CrossBridgeConfig) {
    this.config = config;
    this.observerUrl = config.observerUrl || process.env.CROSSBRIDGE_OBSERVER_URL || 'http://localhost:8765';
    this.enabled = config.enabled !== false && process.env.CROSSBRIDGE_ENABLED !== 'false';
    
    if (this.enabled) {
      console.log(`CrossBridge Playwright reporter enabled for project: ${config.projectId}`);
    }
  }

  onTestBegin(test: TestCase, result: TestResult): void {
    if (!this.enabled) return;

    const event: CrossBridgeEvent = {
      event_type: 'test_start',
      framework: 'playwright',
      test_id: test.titlePath().join(' '),
      timestamp: new Date().toISOString(),
      metadata: {
        title: test.title,
        file: test.location.file,
        line: test.location.line,
        project: test.parent.project()?.name,
        tags: test.tags,
        timeout: test.timeout
      },
      application_version: process.env.APP_VERSION,
      product_name: process.env.PRODUCT_NAME,
      environment: process.env.ENVIRONMENT || 'test'
    };

    this.emitEvent(event);
  }

  onTestEnd(test: TestCase, result: TestResult): void {
    if (!this.enabled) return;

    const event: CrossBridgeEvent = {
      event_type: 'test_end',
      framework: 'playwright',
      test_id: test.titlePath().join(' '),
      timestamp: new Date().toISOString(),
      status: this.mapStatus(result.status),
      duration_ms: result.duration,
      error_message: result.error?.message,
      metadata: {
        title: test.title,
        file: test.location.file,
        retry: result.retry,
        attachments: result.attachments.length,
        steps: result.steps.length,
        project: test.parent.project()?.name
      },
      application_version: process.env.APP_VERSION,
      product_name: process.env.PRODUCT_NAME,
      environment: process.env.ENVIRONMENT || 'test'
    };

    this.emitEvent(event);
  }

  onStepBegin(test: TestCase, result: TestResult, step: any): void {
    if (!this.enabled) return;

    const event: CrossBridgeEvent = {
      event_type: 'step',
      framework: 'playwright',
      test_id: test.titlePath().join(' '),
      timestamp: new Date().toISOString(),
      metadata: {
        step_title: step.title,
        step_category: step.category,
        step_location: step.location
      }
    };

    this.emitEvent(event);
  }

  private mapStatus(status: string): string {
    const statusMap: Record<string, string> = {
      'passed': 'passed',
      'failed': 'failed',
      'timedOut': 'failed',
      'skipped': 'skipped',
      'interrupted': 'error'
    };
    return statusMap[status] || 'unknown';
  }

  private async emitEvent(event: CrossBridgeEvent): Promise<void> {
    try {
      await fetch(`${this.observerUrl}/events`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(event),
        timeout: 1000 // 1 second timeout to not block tests
      });
    } catch (error) {
      // Silently fail - never block test execution
      console.debug(`CrossBridge event emission failed: ${error}`);
    }
  }
}

export { CrossBridgeReporter };
"""


def generate_playwright_hook(output_path: str):
    """Generate TypeScript hook file for Playwright projects"""
    with open(output_path, 'w') as f:
        f.write(PLAYWRIGHT_TYPESCRIPT_HOOK)
    print(f"Generated Playwright hook at: {output_path}")


# Python SDK integration for Playwright Python API
try:
    from playwright.sync_api import Page
    from core.observability.hook_sdk import CrossBridgeHookSDK
    
    class PlaywrightPythonHook:
        """
        Python API for Playwright hook integration.
        
        Usage:
            from crossbridge.hooks.playwright_hook import PlaywrightPythonHook
            
            hook = PlaywrightPythonHook()
            
            def test_example(page: Page):
                hook.emit_test_start("test_example")
                page.goto("https://example.com")
                hook.emit_test_end("test_example", "passed", 1500)
        """
        
        def __init__(self):
            self.sdk = CrossBridgeHookSDK()
        
        def emit_test_start(self, test_id: str, metadata: dict = None):
            """Emit test start event"""
            self.sdk.emit_test_start("playwright", test_id, metadata)
        
        def emit_test_end(self, test_id: str, status: str, duration_ms: int, metadata: dict = None):
            """Emit test end event"""
            self.sdk.emit_test_end("playwright", test_id, status, duration_ms, metadata=metadata)
        
        def emit_page_visit(self, test_id: str, url: str):
            """Emit page navigation event"""
            self.sdk.emit_custom_event(
                framework="playwright",
                test_id=test_id,
                event_type="ui_interaction",
                metadata={'action': 'navigate', 'url': url}
            )

except ImportError:
    # Playwright not installed
    pass


if __name__ == "__main__":
    # Generate TypeScript hook when run directly
    import sys
    output = sys.argv[1] if len(sys.argv) > 1 else "crossbridge-playwright-reporter.ts"
    generate_playwright_hook(output)
